[build]
  command = "npm run build"
  publish = "."

[settings]
  # Enable server-side functions for n8n
  functions = "functions"

[[redirects]]
  from = "/webhook/*"
  to = "/.netlify/functions/n8n-webhook/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "npm start"
  port = 5678
  publish = "."